#!\bin\bash
# i3 panel config. Powerline style.

panel_fifo="/tmp/i3_lemonbar_${USER}"
geometry="x18"
font="Literation Mono Powerline:size=11"
iconfont="FontAwesome:size=13"
res_w=$(xrandr | grep "current" | awk '{print $8a}')
snd_cha=$(amixer get Master | grep "Playback channels:" | awk '{if ($4 == "") {printf "%s: Playback", $3} else {printf "%s %s: Playback", $3, $4}}')

# Alarm settings
cpu_alert=4                         # % cpu use
net_alert=5                         # K net use
bat_alert=20                        # % battary left
bat_full=70                         # % charge considered as full 

# update setting, in seconds (conky update in i3_lemonbar_conky
upd_vol=3                           # Volume update
upd_mail=300                        # Mail check update
upd_mpd=5                           # MPD song update

# color definitions 
color_back="#FF1D1F21"              # Default background
color_fore="#FFC5C8C6"              # Default foreground
#color_head="#FFB5BD68"              # Background for first element
color_head="#FF0087AF"              # Background for first element
color_sec_b1="#FF282A2E"            # Background for section 1
color_sec_b2="#FF454A4F"            # Background for section 2
color_sec_b3="#FF60676E"            # Background for section 3
color_icon="#FF979997"              # For icons
color_mail="#FFCE935F"              # Background color for mail alert
color_chat="#FFCC6666"              # Background color for chat alert
color_cpu="#FF5F819D"               # Background color for cpu alert
color_net="#FF5E8D87"               # Background color for net alert
color_bat="#FF5F0000"               # Background color for bat alert
color_disable="#FF1D1F21"           # Foreground for disable elements
color_wsp="#FFAFD700"               # Background for selected workspace

#default space between sections
if [ ${res_w} -gt 1024 ]; then
  stab='  '
  stab=' '
fi

# Char glyps for powerline fonts
sep_left=""                        # Powerline separator left
sep_right=""                       # Powerline separator right
sep_l_left=""                      # Powerline light separator left
sep_l_right=""                     # Powerline light sepatator right

# Icon glyphs from FontAwsome
icon_cpu=""                        # CPU icon
icon_clock=""                      # Clock icon
icon_cal=""                        # Calender icon
icon_mem=""                        # MEM icon
icon_wireless=""                   # Wireless icon
icon_wired=""                      # MEM icon
icon_dl=""                         # Download icon
icon_ul=""                         # Upload icon
icon_vol=""                        # Volume icon
icon_hd=""                         # HD / icon
icon_home=""                       # HD /home icon
icon_mail=""                       # Mail icon
icon_chat=""                       # IRC/Chat icon
icon_music=""                      # Music icon
icon_prog=""                       # Window icon
icon_contact=""                    # Contact icon
icon_wsp=""                        # Workspace icon
icon_batf=""                       # Battery full
icon_bath=""                       # Battery half
icon_bate=""                       # Battery empty
icon_batchg=""                     # Battery is charging
icon_load=""                       # Load avagrage

